### ISSUE TITLE
Link to rendered lesson in Contributing guide is broken

### ISSUE THREAD

**Issue by bencomp** [datacarpentry/openrefine-socialsci#106]
Under "Where to contribute" in CONTRIBUTING.md, the first list item reads

> If you wish to change this lesson, please work in https://github.com/datacarpentry/openrefine-socialsci, which can be viewed at https://datacarpentry.github.io/socialsci.

The link to the rendered lesson results in a "Page not found" error, instead of getting you to the actual lesson.

**Comment by PrajwalBorkar** [comment]
I can work on this. Can you tell me which link should I replace this with?

**Comment by bencomp** [comment]
@PrajwalBorkar thanks for the offer! The lesson website is <https://datacarpentry.org/openrefine-socialsci/>.

**Comment by PrajwalBorkar** [comment]
Please review for any changes :)
