### ISSUE TITLE
Move Getting help section and Other Resources episode into missing Discussion section

### ISSUE THREAD

**Issue by bencomp** [datacarpentry/openrefine-socialsci#122]
This is a suggestion that should be a discussion topic for our Curriculum Advisory Committee (CAC) and the community at large.

Several people have pointed out that there is overlap between *Getting help* in the Introduction and the *Other resources* episode. I am certainly among them.

#95 notes the overlap.
#86 notes that the content of the Introduction doesn't match the objectives.
#37 also comments on the contents and objectives of the introduction.
#102 is my unordered list of thought about rearranging the whole lesson, which includes this suggestion to remove *Getting help* from the introduction. I also suggest what to put in the Introduction instead: parts of the second episode.
#117 includes my realisation that we should have a Discussion section that really is about continuing learning about the topic, i.e. things that are now part of Getting Help and Other Resources.

That leads me to this suggestion: move the contents of Getting Help and Other Resources to the missing Discussion section.

A long time ago the then CAC, in #29, suggested a few topics to include in the lesson, like more on GREL or reconciliation, which I think are still valid suggestions. But that is something for the new CAC to comment on.

Sidenote: when I teach this lesson, I skip most of the introduction and Other Resources, so I wouldn't even save a lot of time if this suggestion was accepted and new content were to be introduced.

**Comment by bencomp** [comment]
@datacarpentry/curriculum-advisors-social-science your input would be greatly appreciated on this issue!

**Comment by bencomp** [comment]
In the Workbench, there is no "Discussion" section anymore. The glossary is one of the more visible non-episode pages (though it needs updating, #165). If we can add pages with any title under "More", the links to other resources could go to a special "Other resources" page.

Learning to find and explore other resources to continue learning about a software application is of course a quite generic skill that, in my opinion, does not need to be a special part of the lesson.

**Comment by ndporter** [comment]
@bencomp The CAC (2023/07/07 meeting) feels that because OpenRefine is somewhat niche software compared to most of what we teach and so good help is harder to locate, that it's important to include some discussion of additional resources for OpenRefine and GREL in the main lesson, either in the current (final episode) format or another way - and not just the extras.

That said, it would be reasonable to add an instructor note saying these don't all need to be discussed as long as instructors make sure to point out that there are good resources in the lesson to start finding help.

**Comment by bencomp** [comment]
This issue needs to be removed from the list in the Instructor note in the Introduction section (and maybe replaced with other issue(s)). See #183
