### ISSUE TITLE
OpenRefine community no longer uses Google Groups

### ISSUE THREAD

**Issue by bencomp** [datacarpentry/openrefine-socialsci#135]
As mentioned in https://github.com/datacarpentry/OpenRefine-ecology-lesson/pull/278, community support should be sought in a new location. The Google Group has been replaced by a forum. This requires updates to links in our Getting Help section (although I feel this should be part of the Discussion page that needs to be created: #122).

**Comment by antonyni** [comment]
Hi, I can change the google group link to the new link from discourse.org
