### ISSUE TITLE
Broken / unknown link

### ISSUE THREAD

**Issue by gtlaflair** [datacarpentry/openrefine-socialsci#15]
There is a missing link in the guide.md. The link should take a person to a description of the datasets used in the social sciences lessons. Does anyone know where the description is?

https://github.com/datacarpentry/openrefine-socialsci/blob/gh-pages/_extras/guide.md

**Comment by tracykteal** [comment]
Thanks. This is being updated in https://github.com/datacarpentry/openrefine-socialsci/pull/17
