### ISSUE TITLE
remove prefix from references to variables in the episodes

### ISSUE THREAD

**Issue by gtlaflair** [datacarpentry/openrefine-socialsci#22]
It looks like the prefixes in the dataset have been deleted as requested  #21 . They are also used to reference the columns of the dataset (see the last exercise here; i.e., `A09_village`) and need to be removed, too.

https://github.com/datacarpentry/openrefine-socialsci/blob/gh-pages/_episodes/03-filter-sort.md

**Comment by ErinBecker** [comment]
Addressed with https://github.com/datacarpentry/openrefine-socialsci/pull/23

**Comment by tracykteal** [comment]
@gtlaflair does this look resolved with #23, now merged?

**Comment by ErinBecker** [comment]
Closed with #23.

**Comment by gtlaflair** [comment]
You bet! Sorry for the slow reply to the pull request! Thanks @ErinBecker!
