### ISSUE TITLE
add missing content

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/openrefine-socialsci#3]
The following is a list of missing content for this lesson. Please check off items when they have been addressed:

[Episode 2](http://www.datacarpentry.org/openrefine-socialsci/02-working-with-openrefine/)
- [x] keypoints
- [x] time estimates (teaching and exercises)

[Episode 6](http://www.datacarpentry.org/openrefine-socialsci/06-scripts/)
- [x] time estimates (teaching and exercises)

[Reference](http://www.datacarpentry.org/openrefine-socialsci/reference/)
- [x] glossary

[Discussion](http://www.datacarpentry.org/openrefine-socialsci/discuss/)
- [x] this page is empty, can be removed

[Figures](http://www.datacarpentry.org/openrefine-socialsci/figures/)
- [x] this page is empty, can be removed

[Setup](http://www.datacarpentry.org/openrefine-socialsci/setup/)
- [x] Software box is empty

Instructors guide
- [x] this page is missing

**Comment by gtlaflair** [comment]
I made a pull request that (I think) addresses the boxes I checked.

**Comment by ErinBecker** [comment]
Nope 😀

**Comment by ErinBecker** [comment]
Thanks for all your great work on this list @gtlaflair!

**Comment by gtlaflair** [comment]
Thanks @ErinBecker! It is quite fun and rewarding. I'll start (slowly) working on a glossary. I'll probably have something finished up by middle to end of next week.
