### ISSUE TITLE
OpenRefine doesn't appear to work in Internet Explorer

### ISSUE THREAD

**Issue by gcapes** [datacarpentry/openrefine-socialsci#31]
For several learners, OpenRefine started Internet Explorer, but they got a spinny-wheel but nothing more.
Copying and pasting the URL into Chrome worked for everyone.

Perhaps there could be a note (extras/instructor notes?) about this?

**Comment by gtlaflair** [comment]
Thanks for bringing this up. I added a comment in the instructor notes #33.

**Comment by Mooresity** [comment]
I discovered that Microsoft Edge works well. I am not sure if this is same for everyone

**Comment by rorisangmmushi** [comment]
I have also experienced the same issues using OpenRefine with **Internet Explorer** and **Firefox**, but **Chrome** never gave me a problem.

**Comment by bencomp** [comment]
The OpenRefine documentation has (or had) a note that Firefox is not fully compatible, but  in my experience teaching this lesson Firefox works well.
We could still add a note that Edge should work as well. I will take that up.
