### ISSUE TITLE
Adding content to cover OR's Extract/Apply functionality

### ISSUE THREAD

**Issue by paigecm** [datacarpentry/openrefine-socialsci#32]
Please delete the text below before submitting your contribution. 

---

It seems like it would be really useful to cover OpenRefine's Extract/Apply functionality in this lesson. This functionality is visible in the Undo/Redo area. Extract creates a precise representation of all changes made in JSON, which can be copied and saved; Apply allows users to paste that in, and perform all the operations on a new data set. 

I can see this being useful for both social science and natural science data, in particular. Is this something that would be useful for me to write up and add? I don't think it would take a particularly long time to include; possibly within 10 minutes or less.
---

**Comment by fmichonneau** [comment]
I haven't OpenRefine lesson in a very long time. @debpaul do you think there is room to add this? (it's for the social sciences, but it's almost the same lesson as for the ecology curriculum).

**Comment by debpaul** [comment]
Yes @paigecm that would be a great addition. I do think many of us mention / show / include this when we are teaching this lesson - depending on time allotted. It just has not been added formally.

**Comment by gtlaflair** [comment]
Thanks @debpaul. I think, then, it sounds like something to work on if it can be kept to about 10 minutes. @paigecm, are you still interested in tackling this?

**Comment by paigecm** [comment]
Yes! Sorry; I was away from the office so couldn't tackle this, but I'd be happy to, and it's easily something that could be tackled in 10 minutes.
