### ISSUE TITLE
Link to setup not working

### ISSUE THREAD

**Issue by BinxiePeterson** [datacarpentry/openrefine-socialsci#34]
The current link to the setup (https://datacarpentry.org/openrefine-socialsci/setup/) is not working.

The following link works: http://openrefine.org/download.html

**Comment by BinxiePeterson** [comment]
Correction: the following link seems to be the correct one for direction to the setup page:
https://datacarpentry.org/openrefine-socialsci/setup.html

**Comment by gtlaflair** [comment]
Thanks for finding this @BinxiePeterson and opening the issue. I have addressed this in #39
