### ISSUE TITLE
Is "Describe uses and applications" a good Learning Objective; update GREL meaning

### ISSUE THREAD

**Issue by luban19p** [datacarpentry/openrefine-socialsci#37]
Hi there, 

I have been working with the OpenRefine for Social Science Data lesson and have found a couple of issues. Though I realise you would prefer feedback on the OpenRefine for Ecology Data lesson, the first issue also relates to that particular lesson:

1. (This is likely a minor issue) In the Objectives for the Introduction to OpenRefine for Social Science Data, you have 'Describe OpenRefine's uses and applications' - this is not so much a learning objective as a note for the instructor. Could this simply be removed?  
2. Where GREL is introduced in the 'Transforming Data' section of '2. Working with OpenRefine', GREL is still referred to as 'Google Refine Expression Language' in the text and in the screenshot. This might seem a minor point, but for a newbie (like I was a few weeks ago), when they see 'General Refine Expression Language' on their screen this might cause confusion. 

Thank you for your time! :)

Antje

**Comment by gtlaflair** [comment]
Thanks @luban19p for the feedback. I added the discussion tag for point 1. I have opened a pull request  (#40) addressing the comments in point 2.

**Comment by brownsarahm** [comment]
re: 1, I think that learning objective for the introduction is actually a good one.  I think that knowing what a tool can do and why to use it is an important first step to learning _how_ to use it.  In particular, knowing that openrefine is for data _cleaning_ not _analysis_ is important, so maybe refining the objective to make it more specific is good, but I don't think flat removal makes sense.

**Comment by bencomp** [comment]
I will close this issue, as the remaining point – I think – is covered by #103, which is about actually adding content on what you can do with OpenRefine. As part of that effort, we could change the learning objective to "understand how OpenRefine compares to spreadsheet apps and scripting".
