### ISSUE TITLE
Explain goals of the lesson more clearly in the Introduction

### ISSUE THREAD

**Issue by data-librarian** [datacarpentry/openrefine-socialsci#38]
Hi, 

I'd like to suggest a new/modified objective for the Data Cleaning module - Introduction, more focused on learning outcomes.

Participants will be able to process data in order to ensure that it is correct, consistent, and useable by detecting any errors in the data, correcting or removing corruptions in the data, or manually modifying or deleting the coarse data as needed.

Hope this is useful.

Cheers,
Deena Yanofsky

**Comment by bencomp** [comment]
A belated thanks for your suggestion, @data-librarian. At the time of submitting it, the lesson may have been organised a bit differently.

The learning objective that you suggest is a big one, that in my view covers the whole lesson, not a single episode. Let me suggest to make sure the contents of the introduction episode (not the objectives) include something like your suggested objective, to set the 'end goal' for learners.

**Comment by bencomp** [comment]
In my introduction to the lesson I like to stress that we do not cover all of the functionalities that OpenRefine provides and that we do not clean up all the errors in the dataset. This may be good to include in the introduction section as well.

**Comment by bencomp** [comment]
I've been working on a list of lesson learning objectives:

## Learning objectives

By the end of this lesson, you will be able to:

- create, export and import a project in OpenRefine
- view and work on subsets of rows using facets and text filters
- reduce variations in data through clustering, bulk editing and transformations
- undo and redo actions and export the history of actions
- save cleaned data in a widely supported file format

---

This should go in the Summary and Setup section, like in the [Lesson Development Training](https://carpentries.github.io/lesson-development-training/index.html).
What do people think?

**Comment by bencomp** [comment]
This issue is still listed as needing attention in the Introduction (see #183).
