### ISSUE TITLE
Successful clustering methods for village column

### ISSUE THREAD

**Issue by tgnadt** [datacarpentry/openrefine-socialsci#52]
In the [second lesson "Working with Open Refine"] (https://datacarpentry.org/openrefine-socialsci/02-working-with-openrefine)
under "Using clustering to detect possible typing errors" in step 6, it is stated that 

> You should find no more clusters are found. None of the available methods offered to cluster Ruaca-Nhamuenda with Ruaca or Chirdozo with Chirodzo.

This is incorrect as e.g. for the method `nearest neighbor` with `ppm` selected, `Radius` set to "4" and `Block Chars` set to "1", these clusters are correctly identified, which is also shown on this ![screenshot](https://user-images.githubusercontent.com/28293474/66303526-79d5c980-e8fb-11e9-997b-cf83e7d6e6f1.png)
There are also other clustering settings that lead to this result.

Since directly below the steps it is mentioned that using different or more clustering and merging methods here will result in different results later on, I am not sure what a change here would affect, which is why I am submitting this as an issue.

**Comment by mariadelmarq** [comment]
Latest pull request https://github.com/datacarpentry/openrefine-socialsci/pull/78 addresses this issue, cab be safely closed now.
