### ISSUE TITLE
Explain if/when data leaves computer in Introduction episode

### ISSUE THREAD

**Issue by sharynys** [datacarpentry/openrefine-socialsci#63]
It is probably worth pre-emptively answering, in the Introduction, a question researchers often ask ... Is my data safe or is it being copied or uploaded? This is almost answered (indirectly) in the "Before we get started" section, but I'd highlight it as a "Feature". 

This will remind novice users to be aware of where their data is going (which can be confusing in these days of xAAS), while reassuring the 'aware' user that their data doesn't need to go anywhere and can remain local.

**Comment by brownsarahm** [comment]
I think this is a good point to address. Could you submit a Pull request that shows how you would address this?

**Comment by mariadelmarq** [comment]
Latest pull request https://github.com/datacarpentry/openrefine-socialsci/pull/78 addresses this issue, cab be safely closed now.

**Comment by bencomp** [comment]
I proposed this instructor note in #155. How do you feel about this?

> ### Data privacy when using APIs or reconciliation
> 
> Most functionality does not require an Internet connection and keeps your data within the computer. Some functions, however, like looking up data from URLs or reconciling values in your dataset with online services, necessarily require that data is sent to the online services. While this lesson does not cover these functions, it may be important to know
> how data could be shared with outside parties, especially if you work with sensitive or confidential data.

**Comment by sharynys** [comment]
I think this resolves the issue nicely.
________________________________
