### ISSUE TITLE
Explain difference with spreadsheet editor; add info on running OR on server

### ISSUE THREAD

**Issue by MarissaGriesel** [datacarpentry/openrefine-socialsci#79]
Morning all,

A few suggestions for the Introduction to OR lesson (https://datacarpentry.org/openrefine-socialsci/01-introduction/index.html):

*In both workshops where I have been involved either as participant or helper, students were unsure about when to use a spreadsheet editor such as Excel or when to rather use OpenRefine. This may be clarified in the "motivation" section by changing the first bullet point:

_OpenRefine is not a spreadsheet editor like Excel or LibreOffice and it is not used during the initial data collection stage, but rather a platform to help you see patterns or categories in your data and to clear up any errors in your data. OpenRefine provides a set of tools to allow you to identify and amend messy data._
(Perhaps one or two direct comparisons of things you would do using the two different tools as examples or an exercise to show the difference would also be useful.)

*There is a full stop in the header "Getting Help for OpenRefine" which needs to be removed.
Also after "Using undo and redo" (https://datacarpentry.org/openrefine-socialsci/02-working-with-openrefine/index.html)
and "Sorting by multiple columns" (https://datacarpentry.org/openrefine-socialsci/03-filter-sort/index.html)

*A full stop is missing in the last bullet under "Key Points" - OpenRefine will automatically track any steps allowing you to backtrack as needed and providing a record of all work done**.**

*I would also suggest removing some of the columns from the SAFI dataset for use with this lesson. There is a lot of scrolling back and forth to find for instance the column with roof types in workshops :-) 

*A last suggestion is to add some info on running OpenRefine from a server as a considerable amount of participants seemed to prefer this option during our last workshop, especially those who do not have admin rights to their laptops and have difficulties installing new software.

Let me know if you need any other info.

**Comment by brownsarahm** [comment]
These are great suggestions, thanks!

This sound like 3 nice pull requests:
1.  the missing/ extra full stops
1.  for the changes to the motivation 
1. info on the running as a server option to the setup page. 

Reducing columns is mentioned in #35.  That's a longer discussion, though, so this link noting a second request will be a part of the record on that discussion.

**Comment by bencomp** [comment]
I've made some suggestions for comparing OpenRefine to a spreadsheet editor and to scripting in #103. Other suggestions for updating the motivations are also in that issue, as well as in #86.

I would like to stress that you should not need administrative rights to download and run OpenRefine, although I'm not sure. I know that it's possible to run OpenRefine on a server, but it's not recommended as you could more easily get into other people's projects (depending on the setup).

Although not everything has been addressed and approved for updating/inclusion yet, I will close this issue and ask to please continue the discussion in the other issues. Please let me know if you disagree, I'm happy to reopen this issue.
