### ISSUE TITLE
Trailing and leading white spaces missing? (Submitted by email for Instructor Training)

### ISSUE THREAD

**Issue by ErinBecker** [datacarpentry/openrefine-socialsci#80]
I am submitting this issue on behalf of a contributor who submitted it through email. See text below:

In the Trim Leading and Trailing Whitespace part of the Working with OpenRefine episode, the data already appear to be cleaned. I am only getting four choices in the text facet without any transforms. I tried to find another column in the dataset that could be substituted for this example, but couldn't find one with inconsistent white spaces. Perhaps the teaching dataset needs to be made messy again?

**Comment by mariadelmarq** [comment]
With OpenRefine version 3.4 the option to trim leading and trailing whitespaces from all columns appears checked by default during data import. Latest pull request https://github.com/datacarpentry/openrefine-socialsci/pull/78 addresses this issue already, can be closed.

**Comment by ErinBecker** [comment]
Thank you!
