### ISSUE TITLE
Rearrange lesson on exporting and saving

### ISSUE THREAD

**Issue by akshayparopkari** [datacarpentry/openrefine-socialsci#84]
Hi, while teaching the workshop, I realized that exporting and saving [lesson](https://datacarpentry.org/openrefine-socialsci/06-saving/index.html) goes over exporting the project first and then saving the changed file. I found it useful teach saving the file first and then exporting the project. This strategy helped with the lesson flow. This might be useful to others who are teaching OpenRefine ✌️

**Comment by bencomp** [comment]
Hi @akshayparopkari, thanks for bringing this up. I feel I have the same experience, as it's more rare that I need to export the whole project. Let me check with the others how they think about switching the order.

**Comment by bencomp** [comment]
I see in the [Library Carpentry lesson on OR](https://librarycarpentry.org/lc-open-refine/12-export-transformation/index.html) that exporting the project isn't discussed at all. They do have a note about (accidentally) exporting a subset of data, which we don't and probably should include.

I'm in favour of changing the order and adding a note about exporting a subset, so the new structure could be:

1. exporting data
    - why export? (refer to not working on data file directly)
    - exporting a subset
1. exporting the project
    - why this could be useful

**Comment by bencomp** [comment]
@akshayparopkari Could you perhaps have a look at #169? I did more than move the parts around; I adjusted the wording of the chapter's (i.e. episode's) objectives, questions and key points, used callouts and made sure the text reads more easily. There are a few things I'm not complete sure about, even though I feel it is better than before.
Thanks!
