### ISSUE TITLE
Check for links to operefine documentation

### ISSUE THREAD

**Issue by brownsarahm** [datacarpentry/openrefine-socialsci#85]
openrefine docs are being changed soon, so we should be prepare to update any pointers to them

>This heads-up is just to flag that if you have any links to OpenRefine documentation in your lessons you may need to update the links once the new documentation is published. We’re still working on finalising the documentation and it is always going to be a work in progress - so we’re always open to improving it - but you can see the updated documentation as it currently stands at https://docs.openrefine.org/

**Comment by ha0ye** [comment]
Specifically the links in the episode 07 for other resources:
```
* [OpenRefine Documentation for Users](https://github.com/OpenRefine/OpenRefine/wiki/Documentation-For-Users)
* [OpenRefine documentation Wiki site](https://github.com/OpenRefine/OpenRefine/wiki/Documentation-For-Users)
```

**Comment by evanwill** [comment]
I updated all the old Wiki links to the new User Manual in PR  #87 .
The new manual is nice!
