### ISSUE TITLE
Mention (no) admin rights, adjust learning objectives in introduction, open resources in tabs

### ISSUE THREAD

**Issue by Talishask** [datacarpentry/openrefine-socialsci#90]
I'm a member of The Carpentries staff and I'm submitting this issue on behalf of another member of the community. In most cases, I won't be able to follow up or provide more details other than what I'm providing below.

---

In the [setup page](https://datacarpentry.org/openrefine-socialsci/setup.html), you may mention that installing OpenRefine does not require administrative rights. People using work computers without admin rights may think they can't install it like other software, but indeed, you can install OpenRefine without admin rights.

In the [introduction ](https://datacarpentry.org/openrefine-socialsci/01-introduction/index.html) part, 1. the learning objectives don't match what is described on that page. The page does not cover Differentiate data cleaning from data organization and Experiment with OpenRefine's user interface. Suggest to change to "Identify features of OpenRefine". 2. When explaining create project, currently the sample data looks fine, but if users use their own data, they may get unrecognized characters. Maybe mention "In that case, select your text encoding method to US-ASCII"

Under [working with OpenRefine](https://datacarpentry.org/openrefine-socialsci/02-working-with-openrefine/index.html), this sentence is confusing "Note that at step 1, you could upload data in a standard form from a web address by selecting Get data from Web Addresses (URLs). However, this won't work for all URLs". Need explanation of what works or not works.

In [Other resources in OpenRefine section](https://datacarpentry.org/openrefine-socialsci/07-resources/index.html), I would suggest to change the links to other resources to open in another tab. Currently, if users start to explore that link, they will be hard to go back to the lesson.

Overall suggestions:

- · The sample data has a lot of columns that are not used. It's hard to find a column to follow. Maybe delete some columns and leave only the ones used in class?
- · Personally, I think the class may be reorganized. Currently, there are a lot of information in "working with OpenRefine" section. For example, Transforming data using GREL could be moved to the "examine numbers" section. That part is also doing data transformation. I would start by using the common transfer, then introducing GREL. GREL might be a little bit tricky for beginners, so I would not introduce in the earlier part of the class.

**Comment by bencomp** [comment]
Thanks for sharing these suggestions! Some have been mentioned in other issues, but others are actionable.
See #56, #86, #60 and #35, for example.

I will add that you don't need administrative rights for installation.

Choosing US-ASCII as the character encoding when text looks 'jumbled' is probably not the best suggestion, but it could be helpful to explain that character encodings may influence how text is loaded. However, I feel that you could easily go off track trying to explain it. Suggestions are welcome!

Opening links in new windows or tabs would require adjusting the lesson template and is therefore out-of-scope for this lesson.

I will open a new issue about balancing the content of the episodes. That is something that requires input from more people, so I think it's better to have that discussion separately.
