### ISSUE TITLE
Open Refine defaulting to internet explorer on some devices

### ISSUE THREAD

**Issue by tsangutei** [datacarpentry/openrefine-socialsci#93]
I use different devices to access Open Refine, but I have had a recurring issue trying to launch in one institution issued device.

On this particular device, every time I try to create a project, it automatically launches on internet explorer and just will not create. I finally copied the URL to a chrome browser and the project creates. I don't know if this is a unique issue with this device, but that's what I had to do to create projects.

Thanks.

**Comment by brownsarahm** [comment]
Thank you @tsanguteifor your contribution. We currently have on the [setup page](https://datacarpentry.org/openrefine-socialsci/setup.html) to change the default browser to be chrome or firefox and that openrefine will not run in internet explorer. 

Would you like to add your work-around as a tip or do you think the setup instructions are enough?

**Comment by bencomp** [comment]
In the same list that says to make Firefox or Chrome the default browser, there is an instruction to point the browser to the correct address. I think this means the issue has been addressed.
