### ISSUE TITLE
Text in Chapter 2 links to Ecology lessons instead of Social Sciences lesson

### ISSUE THREAD

**Issue by astridorth** [datacarpentry/openrefine-socialsci#94]
In [Episode 2 of the OR for Social Sciences Lesson](https://datacarpentry.org/openrefine-socialsci/02-working-with-openrefine/index.html) under More on Facets there is a link for further reading about **Numeric and Scatterplot facets**. This link refers to episode Examining Numbers in OR. 
The link address is http://www.datacarpentry.org/OpenRefine-ecology-lesson/03-numbers/

So, at this point one is leaving the Social Sciences Lesson and switches to the Ecology lesson. If then following the lesson flow (e.g. forward/backward arrows), one is in the wrong lesson, which is not easy to notice, as structure of lesson and episode names are identical between Social Sciences and Ecology. 

Suggestion: change this link to the identical episode Examining Numbers in the Social Sciences lesson https://datacarpentry.org/openrefine-socialsci/04-numbers/index.html

**However**, this same episode there does only contain details on **numeric facets**, but does not cover **scatterplot facets**. Therefore, either the text needs to be altered as well, or the additional part about scatterplots should be added to the episode for Social Sciences.
If the mix of lessons was intentional, maybe the text could make clear, that the link is outside the lesson and not a reference to content that will be covered later in the lesson.

Further hint: in Social Sciences the episode number for Examining Numbers in text and link is "04". In Ecology the episode numbers in the text are the same, but in URLs are all -1.

**Comment by bencomp** [comment]
The transition to The Workbench broke the link.

**Comment by bencomp** [comment]
As explained in #156, I think I changed the "More on Facets"/"Other types of Facets" callout in a way that would fix the issues discussed here.
