### ISSUE TITLE
Consistent use of 'facet' and 'filter'; script exercise missing; overlap in introduction and other resources

### ISSUE THREAD

**Issue by leannethelibrarian** [datacarpentry/openrefine-socialsci#95]
Hi folks 👋 

I'm submitting a few suggestions for this lesson, as part of the checkout process:

Filtering & sorting episode:
- Filtering section, step 1 - refers to a filter as a facet ("A respondent_roof_type facet"). I think learners would find this confusing as filters & facets are treated as separate things within the OpenRefine UI, even though they appear in the same panel. (Please ignore if I am wrong and filters are officially just a type of facet - but there's nothing in the lesson to suggest this)
- Sort section, exercise - the field name is spelled incorrectly within the solution ("gps:Altitude" should be "gps_Altitude")

Examining numbers episode:
- Numbers section, paragraph 2 - again, refers to a filter as a facet ("be sure to remove any text filter facets"). 
- Numbers section, exercixe - column name is listed as "no_members" when it is actually "no_membrs"

Scripts episode:
- Overview - it says "exercises 10 min" but there are no exercises indicated for this lesson.
- Saving you work as a script section - bullet "1" appears twice (before and after the screenshot)

Other resources episode:
- There is conceptually some similarity between this episode and the material in the Introduction episode (Getting help for OpenRefine section). I think the Other resources episode would benefit from including the information about the user community that can provide support and answer questions. This could be accomplished either by adding more info to the Other resources episode or by linking back to the Introduction episode. But it seems incomplete to refer to other learning resources without also mentioning the community resources.

Hope some of these are helpful. Thanks!

**Comment by bencomp** [comment]
See #102 for more ideas on the introduction. I think the "getting help" section should be removed.

**Comment by ostephens** [comment]
The Facets and Filters terminology is confusing in OpenRefine. My view is:

**Comment by bencomp** [comment]
Thanks for the suggestion, @ostephens! That sounds like a good way to explain what they are and what they do. I'll take this as a suggested solution in a specific issue.

When I teach I usually also mention that people can recognise facets from online shops, even if they never heard the term 'facet' before.

**Comment by bencomp** [comment]
A more explicit suggestion to move the Getting Help section from the Introduction is now its own issue: #122. Since that is a big adjustment to the lesson, the Curriculum Advisory Committee will have to get involved.
I think that covers all points made in this issue, so I will close it.

Again, thanks for your suggestions.
