### ISSUE TITLE
Facets:  two grammatical changes

### ISSUE THREAD

**Issue by davelowetx** [datacarpentry/openrefine-socialsci#96]
Under Facets, two suggested edits bolded and italicized below ("help" and "allows"):

Facets are one of the most useful features of OpenRefine and can help both get an overview of the data in a project as well as **_help_** you bring more consistency to the data. OpenRefine supports faceted browsing as a mechanism for seeing a big picture of your data, and filtering down to just the subset of rows that you want to change in bulk.
A ‘Facet’ groups all the like values that appear in a column, and then **_allows_** you to filter the data by these values and edit values across many records at the same time.

**Comment by bencomp** [comment]
Thanks for your contribution, @davelowetx. I created #97 for this.
